version: '3.8'

services:
  mysql_db:
    image: mysql:8.0.36-debian
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=forum_hub_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_volume:/var/lib/mysql


volumes:
  mysql_db_volume: