CREATE TABLE IF NOT EXISTS tb_topics(
    id BINARY(16) NOT NULL PRIMARY KEY,
    title VARCHAR(70) NOT NULL UNIQUE,
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(12) NOT NULL
)